/* @TODO stricter */
export const PASSWORD_VALIDATION_PATTERN = /[a-zA-Z0-9]{8,24}/
export const PASSWORD_VALIDATION_ERROR = 'PASSWORD_VALIDATION_ERROR'

export const USERNAME_VALIDATION_PATTERN = /[a-zA-Z][a-zA-Z0-9\_\-\.\+\<\>]{3,24}/
export const USERNAME_VALIDATION_ERROR = 'USERNAME_VALIDATION_PATTERN'
